(kwd_add) @keyword
(kwd_external) @keyword
(kwd_procedure) @keyword
(kwd_all) @keyword
(kwd_fetch) @keyword
(kwd_public) @keyword
(kwd_alter) @keyword
(kwd_file) @keyword
(kwd_raiserror) @keyword
(kwd_and) @keyword
(kwd_fillfactor) @keyword
(kwd_read) @keyword
(kwd_any) @keyword
(kwd_for) @keyword
(kwd_readtext) @keyword
(kwd_as) @keyword
(kwd_foreign) @keyword
(kwd_reconfigure) @keyword
(kwd_freetext) @keyword
(kwd_references) @keyword
(kwd_authorization) @keyword
(kwd_freetexttable) @keyword
(kwd_replication) @keyword
(kwd_backup) @keyword
(kwd_from) @keyword
(kwd_restore) @keyword
(kwd_begin) @keyword
(kwd_full) @keyword
(kwd_restrict) @keyword
(kwd_between) @keyword
(kwd_function) @keyword
(kwd_return) @keyword
(kwd_break) @keyword
(kwd_goto) @keyword
(kwd_revert) @keyword
(kwd_browse) @keyword
(kwd_grant) @keyword
(kwd_revoke) @keyword
(kwd_bulk) @keyword
(kwd_group) @keyword
(kwd_right) @keyword
(kwd_by) @keyword
(kwd_having) @keyword
(kwd_rollback) @keyword
(kwd_cascade) @keyword
(kwd_holdlock) @keyword
(kwd_rowcount) @keyword
(kwd_case) @keyword
(kwd_identity) @keyword
(kwd_rowguidcol) @keyword
(kwd_check) @keyword
(kwd_identity_insert) @keyword
(kwd_rule) @keyword
(kwd_checkpoint) @keyword
(kwd_identitycol) @keyword
(kwd_save) @keyword
(kwd_close) @keyword
(kwd_if) @keyword
(kwd_schema) @keyword
(kwd_clustered) @keyword
(kwd_in) @keyword
(kwd_securityaudit) @keyword
(kwd_coalesce) @keyword
(kwd_index) @keyword
(kwd_select) @keyword
(kwd_collate) @keyword
(kwd_inner) @keyword
(kwd_semantickeyphrasetable) @keyword
(kwd_column) @keyword
(kwd_insert) @keyword
(kwd_semanticsimilaritydetailstable) @keyword
(kwd_commit) @keyword
(kwd_intersect) @keyword
(kwd_semanticsimilaritytable) @keyword
(kwd_compute) @keyword
(kwd_into) @keyword
(kwd_session_user) @keyword
(kwd_constraint) @keyword
(kwd_is) @keyword
(kwd_set) @keyword
(kwd_contains) @keyword
(kwd_join) @keyword
(kwd_setuser) @keyword
(kwd_containstable) @keyword
(kwd_key) @keyword
(kwd_shutdown) @keyword
(kwd_continue) @keyword
(kwd_kill) @keyword
(kwd_some) @keyword
(kwd_convert) @keyword
(kwd_left) @keyword
(kwd_statistics) @keyword
(kwd_create) @keyword
(kwd_like) @keyword
(kwd_system_user) @keyword
(kwd_cross) @keyword
(kwd_lineno) @keyword
(kwd_table) @keyword
(kwd_current) @keyword
(kwd_load) @keyword
(kwd_tablesample) @keyword
(kwd_current_date) @keyword
(kwd_merge) @keyword
(kwd_textsize) @keyword
(kwd_current_time) @keyword
(kwd_national) @keyword
(kwd_then) @keyword
(kwd_current_timestamp) @keyword
(kwd_nocheck) @keyword
(kwd_to) @keyword
(kwd_current_user) @keyword
(kwd_nonclustered) @keyword
(kwd_top) @keyword
(kwd_cursor) @keyword
(kwd_not) @keyword
(kwd_tran) @keyword
(kwd_database) @keyword
(kwd_null) @keyword
(kwd_transaction) @keyword
(kwd_dbcc) @keyword
(kwd_trigger) @keyword
(kwd_deallocate) @keyword
(kwd_of) @keyword
(kwd_truncate) @keyword
(kwd_declare) @keyword
(kwd_off) @keyword
(kwd_try_convert) @keyword
(kwd_default) @keyword
(kwd_offsets) @keyword
(kwd_tsequal) @keyword
(kwd_delete) @keyword
(kwd_on) @keyword
(kwd_union) @keyword
(kwd_deny) @keyword
(kwd_open) @keyword
(kwd_unique) @keyword
(kwd_desc) @keyword
(kwd_opendatasource) @keyword
(kwd_unpivot) @keyword
(kwd_disk) @keyword
(kwd_openquery) @keyword
(kwd_update) @keyword
(kwd_distinct) @keyword
(kwd_openrowset) @keyword
(kwd_updatetext) @keyword
(kwd_distributed) @keyword
(kwd_openxml) @keyword
(kwd_use) @keyword
(kwd_double) @keyword
(kwd_option) @keyword
(kwd_user) @keyword
(kwd_drop) @keyword
(kwd_or) @keyword
(kwd_values) @keyword
(kwd_dump) @keyword
(kwd_order) @keyword
(kwd_varying) @keyword
(kwd_else) @keyword
(kwd_outer) @keyword
(kwd_view) @keyword
(kwd_end) @keyword
(kwd_over) @keyword
(kwd_waitfor) @keyword
(kwd_errlvl) @keyword
(kwd_percent) @keyword
(kwd_when) @keyword
(kwd_escape) @keyword
(kwd_pivot) @keyword
(kwd_where) @keyword
(kwd_except) @keyword
(kwd_plan) @keyword
(kwd_while) @keyword
(kwd_exec) @keyword
(kwd_precision) @keyword
(kwd_with) @keyword
(kwd_execute) @keyword
(kwd_primary) @keyword
(kwd_exists) @keyword
(kwd_print) @keyword
(kwd_writetext) @keyword
(kwd_exit) @keyword
(kwd_proc) @keyword
(comment) @comment
(multilinecomment) @comment
